### ISSUE TITLE
Error during training.

### ISSUE THREAD

**Issue by preddy5** [qymeng94/DSR#4]
Hey @qymeng94 
Kudos on the great work. Thank you for open-sourcing the code. I have been trying to train on Cifar10 however I have run into errors. I am curious if you have encountered these errors before. I am currently using pytorch 1.10.2.

`python -u cifar/main_single_gpu.py --path ../data --dataset cifar10 --model preresnet.resnet18_lif --name checkpoin`

```
==> Preparing dataset cifar10
Files already downloaded and verified
==> creating model

Epoch: [1 | 200] LR: 0.100000
Traceback (most recent call last):
  File "cifar/main_single_gpu.py", line 398, in <module>
    main()
  File "cifar/main_single_gpu.py", line 235, in main
    train_loss, train_acc = train(trainloader, model, criterion, optimizer, warmup=args.warmup)
  File "cifar/main_single_gpu.py", line 287, in train
    outputs = model(inputs)
  File "/home/creddy/anaconda3/envs/cuda11/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/creddy/anaconda3/envs/cuda11/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/creddy/anaconda3/envs/cuda11/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/creddy/anaconda3/envs/cuda11/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/creddy/anaconda3/envs/cuda11/lib/python3.6/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/creddy/anaconda3/envs/cuda11/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/creddy/anaconda3/envs/cuda11/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/creddy/Work/DSR/cifar/modules/preresnet.py", line 150, in forward
    out = self.layer1(out)
  File "/home/creddy/anaconda3/envs/cuda11/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/creddy/anaconda3/envs/cuda11/lib/python3.6/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/creddy/anaconda3/envs/cuda11/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/creddy/Work/DSR/cifar/modules/preresnet.py", line 38, in forward
    x = self.relu1(self.bn1(x))
  File "/home/creddy/anaconda3/envs/cuda11/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/creddy/Work/DSR/cifar/modules/neuron.py", line 220, in forward
    out = lif(x, self.timesteps, self.Vth, self.tau, self.delta_t, self.alpha)
RuntimeError: Output 9 of BroadcastBackward is a view and its base or another view of its base has been modified inplace. This view is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. You should replace the inplace operation by an out-of-place one.
```

**Comment by preddy5** [comment]
Setting env variable to CUDA_VISIBLE_DEVICES=0 solved the issue. Thank you.
